import React, { useState } from 'react';
import { X, ShieldCheck, KeyRound, CheckCircle2, Lock, Smartphone } from 'lucide-react';

interface MfaVerificationModalProps {
  onClose: () => void;
  onSuccess: () => void;
  adminEmail?: string;
}

export const MfaVerificationModal: React.FC<MfaVerificationModalProps> = ({
  onClose,
  onSuccess,
  adminEmail = 'admin@arma.org.rw'
}) => {
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [verified, setVerified] = useState(false);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (code.trim().length !== 6) {
      setError('Please enter a valid 6-digit TOTP code.');
      return;
    }
    // Simulate verification (any 6 digit or 123456)
    setVerified(true);
    setError('');
    setTimeout(() => {
      onSuccess();
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="relative w-full max-w-md bg-white dark:bg-[#12161A] text-slate-900 dark:text-white rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 sm:p-8 space-y-5 animate-fadeIn">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="text-center space-y-2">
          <div className="w-14 h-14 rounded-2xl bg-[#00A1DE]/10 text-[#00A1DE] flex items-center justify-center mx-auto shadow-inner">
            <ShieldCheck className="w-8 h-8 text-[#FAD201]" />
          </div>
          <h3 className="text-xl font-serif font-bold">
            Administrator 2FA / MFA Challenge
          </h3>
          <p className="text-xs text-slate-500 max-w-xs mx-auto">
            Multi-factor authentication is enforced for ARMA Secretariat Administrators.
          </p>
          <div className="inline-block px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-mono text-[11px] font-bold">
            Target Account: {adminEmail}
          </div>
        </div>

        {verified ? (
          <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-center space-y-2 text-emerald-500 animate-fadeIn">
            <CheckCircle2 className="w-8 h-8 mx-auto" />
            <strong className="block text-sm font-bold">MFA Verification Passed!</strong>
            <p className="text-xs text-emerald-400">Authenticating session token & launching portal...</p>
          </div>
        ) : (
          <form onSubmit={handleVerify} className="space-y-4 text-xs">
            <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-1 text-center">
              <span className="font-mono text-[10px] text-slate-400 font-bold uppercase block flex items-center justify-center gap-1">
                <Smartphone className="w-3.5 h-3.5 text-[#00A1DE]" /> Open Authenticator App (Google / Authy)
              </span>
              <p className="text-slate-500 text-[11px]">
                Enter the 6-digit verification code generated by your authenticator app.
              </p>
            </div>

            <div>
              <label className="block font-semibold mb-1 text-slate-700 dark:text-slate-300 text-center">
                6-Digit Security Code
              </label>
              <input
                type="text"
                maxLength={6}
                value={code}
                onChange={(e) => {
                  setCode(e.target.value.replace(/\D/g, ''));
                  setError('');
                }}
                placeholder="123456"
                className="w-full text-center tracking-[0.5em] font-mono text-xl font-bold p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white"
                autoFocus
              />
            </div>

            {error && (
              <p className="text-[11px] text-red-500 font-mono font-bold text-center">{error}</p>
            )}

            <button
              type="submit"
              className="w-full py-3 rounded-2xl bg-[#00A1DE] text-white font-bold hover:bg-[#0081B3] transition-colors flex items-center justify-center gap-2 shadow-lg"
            >
              <KeyRound className="w-4 h-4 text-[#FAD201]" /> Verify MFA Security Key
            </button>
          </form>
        )}
      </div>
    </div>
  );
};
